services:
  - type: web
    name: shop-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your environment variables here:
    # - key: MONGODB_URI
    #   value: your_mongodb_connection_string
    # - key: JWT_SECRET
    #   value: your_jwt_secret